# Numpy'ı Projeye Dahil Etme

In [2]:
import numpy as np


# Numpy ile Temel İşlemler

In [9]:
array = np.array([1,2,3,4,5])

In [11]:
type(array)

numpy.ndarray

In [12]:
array.shape

(5,)

In [13]:
array2 = np.array([1,2,3,4,5,6,7,8,9])

In [15]:
array2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
array2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
array3 = array2.reshape(3,3)
array3.ndim


2

In [45]:
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
array3.size

9

In [51]:
array4 = np.zeros((3,4))

In [52]:
array4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
array5 = np.ones((3,4))

In [55]:
array5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [64]:
array6 = np.empty((5,6))

In [65]:
array6

array([[1.07080684e-311, 9.78249979e-322, 0.00000000e+000,
        0.00000000e+000, 1.06948588e-311, 5.02034658e+175],
       [3.46556446e+179, 4.71474663e-062, 1.48508232e-076,
        7.45863953e-038, 1.36948838e-071, 3.59751658e+252],
       [8.93185432e+271, 4.76484771e+180, 1.47763641e+248,
        1.16096346e-028, 7.69165785e+218, 1.35617292e+248],
       [6.21632800e+174, 1.53389930e-052, 6.75827134e-067,
        4.54684117e+174, 6.78980976e-144, 1.16097020e-028],
       [6.00020917e-067, 2.73458899e-052, 4.08521378e-033,
        1.11763122e+261, 1.16318408e-028, 6.79764374e-310]])

In [66]:
array7 = np.arange(5, 50, 10)

In [67]:
array7

array([ 5, 15, 25, 35, 45])

In [75]:
array8 = np.linspace(0,10,20)

In [76]:
array8

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

# Numpy İle Temel İşlemler

In [78]:
array9 = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])

In [79]:
array10 = np.array([[16,17,18,19,20], [21,22,23,24,25], [26,27,28,29,30]])

In [81]:
array9 + array10

array([[17, 19, 21, 23, 25],
       [27, 29, 31, 33, 35],
       [37, 39, 41, 43, 45]])

In [84]:
array10 - array9

array([[15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15]])

In [85]:
array9 * array10

array([[ 16,  34,  54,  76, 100],
       [126, 154, 184, 216, 250],
       [286, 324, 364, 406, 450]])

In [86]:
array9 / array10

array([[0.0625    , 0.11764706, 0.16666667, 0.21052632, 0.25      ],
       [0.28571429, 0.31818182, 0.34782609, 0.375     , 0.4       ],
       [0.42307692, 0.44444444, 0.46428571, 0.48275862, 0.5       ]])

In [87]:
np.sin(array9)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [88]:
np.exp(array9)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [89]:
array9

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [90]:
array9.T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [4]:
a = np.array([[0,3,5], [5,5,2]])
b = np.array([[4,-2,-2],[3,3,4]])

In [95]:
a.dot(b.T)

array([[-16,  29],
       [  6,  38]])

In [104]:
a

array([[0, 3, 5],
       [5, 5, 2]])

In [105]:
a.sum(axis=0)

array([5, 8, 7])

In [106]:
a.sum(axis=1)

array([ 8, 12])

In [107]:
np.square(a)

array([[ 0,  9, 25],
       [25, 25,  4]], dtype=int32)

In [108]:
np.sqrt(a)

array([[0.        , 1.73205081, 2.23606798],
       [2.23606798, 2.23606798, 1.41421356]])

In [5]:
np.add(a,b)

array([[4, 1, 3],
       [8, 8, 6]])

# Matrisin Belirli Kısımlarını Yazdırma

In [6]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
array[:, 0]

array([1, 4, 7])

In [10]:
array[:, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Numpy Matrisi Yeniden Boyutlandırma

In [11]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
array.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [14]:
array1.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [15]:
array1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
array1.resize(3,4)

In [17]:
array1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# İki Matrisi Birleştirme

In [18]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [20]:
np.vstack((array1,array2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
np.hstack((array1,array2))

array([[ 1,  2,  3,  1,  2,  3],
       [ 4,  5,  6,  4,  5,  6],
       [ 7,  8,  9,  7,  8,  9],
       [10, 11, 12, 10, 11, 12]])